import type { AfpPolicy, PolicyLevel } from "../../shared/afp";
const policy = (
  id: string,
  name: string,
  level: PolicyLevel,
  description: string,
  reference: string,
  locked = false,
): AfpPolicy => ({
  id,
  name,
  level,
  description,
  reference,
  locked,
  revision: 1,
});
export const afpPolicies: AfpPolicy[] = [
  policy("atlas-presentation", "Private Atlas presentation", "Allowed", "Only allowlisted color tokens for the Select Injuries control. No arbitrary CSS or geometry.", "server/afp/presentation.ts"),
  policy(
    "assistant-presentation",
    "Private Coordinator label",
    "Allowed",
    "The trusted SDK may store only the authenticated user's plain-text tab label. Disabling restores the default. No shared UI or executable customization.",
    "server/afp/presentation.ts",
  ),
  policy(
    "rendering-preflight",
    "Rendering recipe inspection",
    "Allowed",
    "The SDK may validate caller-supplied recipe values against the production schema. No evidence reads, rendering jobs or core mutations are permitted.",
    "server/afp/sdk.ts; server/rendering/recipe.ts",
  ),
  policy(
    "ui-additions",
    "UI additions",
    "Allowed",
    "Future additive panels may preserve core navigation and review controls. No code is attached by this policy.",
    "src/main.tsx; src/InjuryWorkspace.tsx",
  ),
  policy(
    "custom-workflows",
    "Custom workflows",
    "Approval Required",
    "Review effects on case data, background work and approval gates.",
    "server/production-routes.ts",
  ),
  policy(
    "custom-agents",
    "Custom AI agents",
    "Approval Required",
    "Only registered implementations and installed skills execute today.",
    "shared/ai.ts; server/ai/settings.ts",
  ),
  policy(
    "additional-databases",
    "Additional databases",
    "Approval Required",
    "Separate ownership, data access and lifecycle must be specified before connecting a feature database.",
    "server/store.ts",
  ),
  policy(
    "external-services",
    "External services",
    "Approval Required",
    "Require scoped credentials and a reviewed service interface.",
    "server/ai/connections.ts",
  ),
  policy(
    "external-storage",
    "External storage",
    "Approval Required",
    "Preserve private access, hashes, versioning and retention.",
    "server/evidence-storage.ts",
  ),
  policy(
    "gpu-compute",
    "GPU compute",
    "Approval Required",
    "Review isolation, measurements, estimated cost and explicit spending authorization.",
    "server/injury-worker.ts",
  ),
  policy(
    "dedicated-runtime",
    "Dedicated runtime",
    "Approval Required",
    "Define runtime isolation and authorized resource limits before activation.",
    "server/index.ts",
  ),
  policy(
    "authentication",
    "Authentication",
    "Protected",
    "Extensions cannot replace or bypass authentication.",
    "server/store.ts; server/app.ts",
    true,
  ),
  policy(
    "tenant-boundaries",
    "Tenant boundaries",
    "Protected",
    "No extension may grant itself access to another user or firm's private data.",
    "server/store.ts: canAccessCase; server/app.ts",
    true,
  ),
  policy(
    "evidence-provenance",
    "Evidence provenance",
    "Protected",
    "Preserve original evidence, hashes, source references and independent review decisions.",
    "server/evidence-storage.ts; server/production-routes.ts",
    true,
  ),
  policy(
    "audit-logging",
    "Disabling audit controls",
    "Protected",
    "Customization cannot disable or erase required audit controls.",
    "server/store.ts: audit; server/afp/management.ts",
    true,
  ),
  policy(
    "billing",
    "Billing",
    "Protected",
    "Pricing metadata cannot grant a feature permission to charge users or alter billing.",
    "server/ai/usage.ts",
  ),
];
