import type { ReadinessItem, ReadinessStatus } from "../../shared/afp";
const item = (
  id: string,
  name: string,
  status: ReadinessStatus,
  description: string,
  evidence: string,
  nextStep: string,
  dependencies: string[] = [],
): ReadinessItem => ({
  id,
  name,
  status,
  ceiling: status === "Implemented" ? "Verified" : status,
  description,
  evidence,
  nextStep,
  dependencies,
  revision: 1,
  lastVerified: null,
});
export const afpReadiness: ReadinessItem[] = [
  item(
    "manifest",
    "AFP Manifest",
    "Implemented",
    "Experimental injury.bot.afp/0.1 has a strict machine-readable schema and validator for ownership, permissions, resources and exact application compatibility. It is injury.bot-specific, not an industry standard.",
    "server/afp/control-plane.ts; shared/afp.ts",
    "Exercise a second contract only after validating this first boundary.",
  ),
  item(
    "protected-core",
    "Protected Core",
    "Partial",
    "Existing auth, tenant and evidence controls are enforced by application routes. Locked AFP policy entries are enforced by the settings API; extension runtime enforcement is not installed.",
    "server/app.ts; server/store.ts; server/afp/policy.ts",
    "Enforce these invariants at the SDK boundary and test malicious extensions.",
  ),
  item(
    "extension-registry",
    "Extension Point Registry",
    "Implemented",
    "Typed declarative registry records real candidate boundaries and their protected behavior. Registration does not dynamically attach code.",
    "server/afp/extension-points.ts; tests/afp-control-plane.test.ts",
    "Rendering preflight and private presentation now have contracts; select the next boundary only after isolated-preview design.",
  ),
  item(
    "user-isolation",
    "Per-user Feature Isolation",
    "Partial",
    "Private presentation and staged workflow packages/runs are isolated by authenticated user and firm. No arbitrary-code sandbox exists.",
    "server/afp/workflows.ts; tests/afp-workflows.test.ts",
    "Extend scoped capabilities beyond the declarative workflow interpreter.",
    ["protected-core", "sdk"],
  ),
  item(
    "external-services",
    "External Service Support",
    "Foundation",
    "Existing firm integrations and provider adapters demonstrate scoped service access, not arbitrary AFP sidecars.",
    "server/ai/connections.ts; server/ai/providers.ts",
    "Create a constrained service adapter and credential boundary.",
    ["sdk"],
  ),
  item(
    "external-databases",
    "External Database Support",
    "Planned",
    "No AFP extension database connector or isolated schema ownership is implemented.",
    "server/afp/resources.ts",
    "Define database ownership and access tokens without exposing the primary database.",
    ["user-isolation", "sdk"],
  ),
  item(
    "dedicated-compute",
    "Dedicated Compute Support",
    "Planned",
    "The current child worker shares the application host. Per-feature dedicated compute is not provisioned.",
    "server/index.ts; server/afp/resources.ts",
    "Define a separate worker contract and authorized compute limits.",
    ["user-isolation"],
  ),
  item(
    "gpu-compute",
    "GPU Compute Support",
    "Planned",
    "The geometric renderer is implemented, but a private GPU service and GPU provisioning are not.",
    "server/injury-worker.ts; server/afp/resources.ts",
    "Prototype the rendering adapter against an isolated service before paid provisioning.",
    ["dedicated-compute", "user-isolation", "cost-accounting"],
  ),
  item(
    "feature-versioning",
    "Feature Versioning",
    "Partial",
    "Private workflow packages have immutable versions and hashes. Saved runs retain their original definition. Contract and policy compatibility are rechecked; executable packages remain future work.",
    "server/afp/workflows.ts; tests/afp-workflows.test.ts",
    "Define executable package compatibility after a separately isolated runtime exists.",
    ["manifest"],
  ),
  item(
    "preview",
    "Preview Environment",
    "Partial",
    "Private declarative workflow previews use the same host UI interpreter with ephemeral checklist/notes state. They do not change the active package or persist preview entries. No generated-code preview environment exists.",
    "src/AfpWorkflows.tsx; scripts/check-coordinator-browser.mjs",
    "Design an isolated executable preview and scoped capability transport.",
    ["user-isolation", "sdk"],
  ),
  item(
    "automated-testing",
    "Automated Testing",
    "Foundation",
    "Base CI exercises routes, geometry, coordinator and AFP metadata. AFP package tests are not yet supported.",
    ".github/workflows/ci.yml; tests/afp-control-plane.test.ts",
    "Run extension contract and behavioral tests before activation.",
    ["sdk"],
  ),
  item(
    "security-validation",
    "Security Validation",
    "Foundation",
    "Authorization and protected-policy tests exist. Arbitrary AFP code, packages and data access cannot yet be security-validated.",
    "tests/afp-management.test.ts; tests/afp-control-plane.test.ts",
    "Add negative SDK capability tests and package validation.",
    ["protected-core", "sdk"],
  ),
  item(
    "rollback",
    "Rollback",
    "Partial",
    "Private workflow activation can restore any prior compatible immutable version without a shared deployment. Disable/remove stops use and retains history. Existing runs stay pinned; no destructive data rollback occurs.",
    "server/afp/workflows.ts; tests/afp-workflows.test.ts",
    "Define migrations before introducing feature data-schema changes.",
    ["feature-versioning", "sdk"],
  ),
  item(
    "cost-accounting",
    "Cost Accounting",
    "Partial",
    "Provider usage and allocation estimates exist. Private feature compute invoices, resource quotas and live voice usage are not metered.",
    "server/ai/usage.ts; src/UsageSettings.tsx",
    "Attribute costs to feature/resource identity and enforce approved resource budgets.",
    ["user-isolation"],
  ),
  item(
    "feature-sharing",
    "Feature Sharing",
    "Planned",
    "Private/Firm/Community/Official are registry metadata. They do not publish or install feature packages.",
    "server/afp/features.ts",
    "Define package ownership, review and distribution.",
    ["feature-versioning", "security-validation"],
  ),
  item(
    "upstream-bugs",
    "Upstream Bug Reporting",
    "Planned",
    "Development records can cite bugs; there is no automated upstream report or patch submission.",
    "server/afp/management.ts",
    "Add sanitized reproduction bundles and authorized upstream submission.",
    ["automated-testing"],
  ),
  item(
    "reconciliation",
    "Update Reconciliation",
    "Planned",
    "Pinned engine builds and verified base releases do not reconcile custom feature changes.",
    "atlas.lock.json; deploy/activate.sh",
    "Test compatibility, conflicts and preservation across base upgrades.",
    ["feature-versioning", "automated-testing", "rollback"],
  ),
  item(
    "mcp",
    "AFP MCP Connection",
    "Planned",
    "The existing Coordinator uses app-native tools. No AFP MCP transport or external orchestration connection is installed.",
    "server/ai/coordinator.ts",
    "Expose a minimal authenticated AFP orchestration surface after SDK contract tests.",
    ["manifest", "sdk"],
  ),
  item(
    "sdk",
    "AFP SDK Boundary",
    "Implemented",
    "Internal SDK v0.1 exposes manifest management, read-only recipe preflight, private presentation and declarative workflow lifecycle/run capabilities. No arbitrary code, renderer execution, filesystem, SQL or external connection is exposed.",
    "server/afp/sdk.ts; tests/afp-sdk.test.ts",
    "Design an isolated preview runtime and artifact boundary before any execution.",
    ["manifest", "protected-core"],
  ),
];
// No score: every isolated-pilot gate must be demonstrated, not averaged away.
export const isolatedPilotCriteria = [
  "manifest",
  "protected-core",
  "extension-registry",
  "user-isolation",
  "preview",
  "automated-testing",
  "security-validation",
  "rollback",
  "sdk",
  "mcp",
];
export function deriveReadiness(items: ReadinessItem[]) {
  const criteria = isolatedPilotCriteria.map((id) => ({
    id,
    label: items.find((i) => i.id === id)?.name || id,
    met: items.find((i) => i.id === id)?.status === "Verified",
  }));
  return {
    label: criteria.every((c) => c.met)
      ? "Ready for isolated pilot validation"
      : "Control-plane foundation · isolated execution not ready",
    criteria,
    blockers: criteria.filter((c) => !c.met).map((c) => c.label),
  };
}
