import type { ReadinessItem, ReadinessStatus } from "../../shared/afp";
const item = (
  id: string,
  name: string,
  status: ReadinessStatus,
  description: string,
  evidence: string,
  nextStep: string,
  dependencies: string[] = [],
): ReadinessItem => ({
  id,
  name,
  status,
  ceiling: status === "Implemented" ? "Verified" : status,
  description,
  evidence,
  nextStep,
  dependencies,
  revision: 1,
  lastVerified: null,
});
export const afpReadiness: ReadinessItem[] = [
  item(
    "manifest",
    "AFP Manifest",
    "Foundation",
    "A versioned injury.bot draft export describes registered boundaries and policies. There is no standardized AFP negotiation or runtime manifest enforcement.",
    "server/afp/control-plane.ts; shared/afp.ts",
    "Specify a minimal manifest schema and enforce one trusted SDK operation.",
  ),
  item(
    "protected-core",
    "Protected Core",
    "Partial",
    "Existing auth, tenant and evidence controls are enforced by application routes. Locked AFP policy entries are enforced by the settings API; extension runtime enforcement is not installed.",
    "server/app.ts; server/store.ts; server/afp/policy.ts",
    "Enforce these invariants at the SDK boundary and test malicious extensions.",
  ),
  item(
    "extension-registry",
    "Extension Point Registry",
    "Implemented",
    "Typed declarative registry records real candidate boundaries and their protected behavior. Registration does not dynamically attach code.",
    "server/afp/extension-points.ts; tests/afp-control-plane.test.ts",
    "Define the request/result contract for one candidate boundary.",
  ),
  item(
    "user-isolation",
    "Per-user Feature Isolation",
    "Foundation",
    "Firm/case isolation exists. No per-user AFP executable feature sandbox exists.",
    "server/store.ts; server/app.ts",
    "Build isolated feature identity and data capabilities.",
    ["protected-core", "sdk"],
  ),
  item(
    "external-services",
    "External Service Support",
    "Foundation",
    "Existing firm integrations and provider adapters demonstrate scoped service access, not arbitrary AFP sidecars.",
    "server/ai/connections.ts; server/ai/providers.ts",
    "Create a constrained service adapter and credential boundary.",
    ["sdk"],
  ),
  item(
    "external-databases",
    "External Database Support",
    "Planned",
    "No AFP extension database connector or isolated schema ownership is implemented.",
    "server/afp/resources.ts",
    "Define database ownership and access tokens without exposing the primary database.",
    ["user-isolation", "sdk"],
  ),
  item(
    "dedicated-compute",
    "Dedicated Compute Support",
    "Planned",
    "The current child worker shares the application host. Per-feature dedicated compute is not provisioned.",
    "server/index.ts; server/afp/resources.ts",
    "Define a separate worker contract and authorized compute limits.",
    ["user-isolation"],
  ),
  item(
    "gpu-compute",
    "GPU Compute Support",
    "Planned",
    "The geometric renderer is implemented, but a private GPU service and GPU provisioning are not.",
    "server/injury-worker.ts; server/afp/resources.ts",
    "Prototype the rendering adapter against an isolated service before paid provisioning.",
    ["dedicated-compute", "user-isolation", "cost-accounting"],
  ),
  item(
    "feature-versioning",
    "Feature Versioning",
    "Foundation",
    "The feature registry validates version metadata and retains revision history. Executable feature packages and compatibility resolution do not exist.",
    "server/afp/features.ts",
    "Add immutable package hashes and base/SDK compatibility checks.",
    ["manifest"],
  ),
  item(
    "preview",
    "Preview Environment",
    "Planned",
    "CI browser fixtures verify the base app. There is no private AFP feature preview environment.",
    "scripts/check-production-browser.mjs",
    "Build a disposable isolated preview with explicit activation.",
    ["user-isolation", "sdk"],
  ),
  item(
    "automated-testing",
    "Automated Testing",
    "Foundation",
    "Base CI exercises routes, geometry, coordinator and AFP metadata. AFP package tests are not yet supported.",
    ".github/workflows/ci.yml; tests/afp-control-plane.test.ts",
    "Run extension contract and behavioral tests before activation.",
    ["sdk"],
  ),
  item(
    "security-validation",
    "Security Validation",
    "Foundation",
    "Authorization and protected-policy tests exist. Arbitrary AFP code, packages and data access cannot yet be security-validated.",
    "tests/afp-management.test.ts; tests/afp-control-plane.test.ts",
    "Add negative SDK capability tests and package validation.",
    ["protected-core", "sdk"],
  ),
  item(
    "rollback",
    "Rollback",
    "Foundation",
    "Base deployment restores the prior release after failed verification. Feature rollback is metadata only and does not restore databases.",
    "deploy/activate.sh; server/afp/features.ts",
    "Implement versioned feature activation and reversal with explicit data-migration rules.",
    ["feature-versioning", "sdk"],
  ),
  item(
    "cost-accounting",
    "Cost Accounting",
    "Partial",
    "Provider usage and allocation estimates exist. Private feature compute invoices, resource quotas and live voice usage are not metered.",
    "server/ai/usage.ts; src/UsageSettings.tsx",
    "Attribute costs to feature/resource identity and enforce approved resource budgets.",
    ["user-isolation"],
  ),
  item(
    "feature-sharing",
    "Feature Sharing",
    "Planned",
    "Private/Firm/Community/Official are registry metadata. They do not publish or install feature packages.",
    "server/afp/features.ts",
    "Define package ownership, review and distribution.",
    ["feature-versioning", "security-validation"],
  ),
  item(
    "upstream-bugs",
    "Upstream Bug Reporting",
    "Planned",
    "Development records can cite bugs; there is no automated upstream report or patch submission.",
    "server/afp/management.ts",
    "Add sanitized reproduction bundles and authorized upstream submission.",
    ["automated-testing"],
  ),
  item(
    "reconciliation",
    "Update Reconciliation",
    "Planned",
    "Pinned engine builds and verified base releases do not reconcile custom feature changes.",
    "atlas.lock.json; deploy/activate.sh",
    "Test compatibility, conflicts and preservation across base upgrades.",
    ["feature-versioning", "automated-testing", "rollback"],
  ),
  item(
    "mcp",
    "AFP MCP Connection",
    "Planned",
    "The existing Coordinator uses app-native tools. No AFP MCP transport or external orchestration connection is installed.",
    "server/ai/coordinator.ts",
    "Expose a minimal authenticated AFP orchestration surface after SDK contract tests.",
    ["manifest", "sdk"],
  ),
  item(
    "sdk",
    "AFP SDK Integration",
    "Planned",
    "Typed draft definitions exist; a trusted AFP SDK application interface is not installed.",
    "shared/afp.ts",
    "Implement one capability-scoped read/preview operation.",
    ["manifest", "protected-core"],
  ),
];
// No score: every isolated-pilot gate must be demonstrated, not averaged away.
export const isolatedPilotCriteria = [
  "manifest",
  "protected-core",
  "extension-registry",
  "user-isolation",
  "preview",
  "automated-testing",
  "security-validation",
  "rollback",
  "sdk",
  "mcp",
];
export function deriveReadiness(items: ReadinessItem[]) {
  const criteria = isolatedPilotCriteria.map((id) => ({
    id,
    label: items.find((i) => i.id === id)?.name || id,
    met: items.find((i) => i.id === id)?.status === "Verified",
  }));
  return {
    label: criteria.every((c) => c.met)
      ? "Ready for isolated pilot validation"
      : "Control-plane foundation · isolated execution not ready",
    criteria,
    blockers: criteria.filter((c) => !c.met).map((c) => c.label),
  };
}
